project:
  type: book
  preview:
    browser: true

book:
  title: "STARS Work Package 1"
  chapters:
  - index.qmd
  - text: "Introduction"
    href: pages/background.qmd
  - text: "Methods"
    href: pages/protocol.qmd
  - part: "Results"
    chapters:
    - pages/reproduction.qmd
    - pages/reflections.qmd
    - pages/repo_evaluation.qmd
    - pages/paper_evaluation.qmd
  - part: "Discussion"
    chapters:
    - pages/discussion.qmd
    - pages/other_studies.qmd
    - pages/framework.qmd
  - pages/acknowledgements.qmd
  favicon: images/stars_logo_blue.png
  search:
    location: navbar
    type: overlay
  navbar:
    collapse: false
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/stars_wp1_summary
  sidebar:
    logo: images/stars_logo_blue.png

format:
  html:
    theme: cosmo
    toc: true