project:
  type: book
  preview:
    browser: true

book:
  title: "STARS Work Package 1: Computational Reproducibility Assessments"
  chapters:
  - index.qmd
  - text: "Introduction"
    href: pages/background.qmd
  - part: "Methods"
    chapters:
    - text: "Protocol"
      href: pages/protocol.qmd
    - text: "Badges"
      href: pages/badges.qmd
  - part: "Results"
    chapters:
    - pages/reproduction.qmd
    - pages/reflections.qmd
    - pages/repo_evaluation.qmd
    - pages/paper_evaluation.qmd
    - pages/compendium.qmd
  - pages/acknowledgements.qmd
  favicon: images/stars_logo_blue.png
  search:
    location: navbar
    type: overlay
  navbar:
    collapse: false
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/stars_wp1_summary
  sidebar:
    logo: images/stars_logo_blue.png

format:
  html:
    theme: cosmo
    toc: true