<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Comparison to other studies – STARS Work Package 1: Computational Reproducibility Assessments</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../pages/framework.html" rel="next">
<link href="../pages/results_discussion.html" rel="prev">
<link href="../images/stars_logo_blue.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">STARS Work Package 1: Computational Reproducibility Assessments</span>
    </a>
  </div>
          <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/pythonhealthdatascience/stars_wp1_summary"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          <div class="quarto-navbar-tools">
</div>
            <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../pages/results_discussion.html">Discussion</a></li><li class="breadcrumb-item"><a href="../pages/other_studies.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Comparison to other studies</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../images/stars_logo_blue.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Overview</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/background.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/protocol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Results</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/reproduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reproduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/reflections.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Reflections from reproductions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/repo_evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Evaluation of the repository</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/paper_evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Evaluation of the article</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/compendium.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Reflections from research compendium and test-run</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Discussion</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/results_discussion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Results discussion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/other_studies.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Comparison to other studies</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Modifying the framework</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/limitations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Limitations</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pages/acknowledgements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Acknowledgements</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#studies-that-assessed-reproducibility" id="toc-studies-that-assessed-reproducibility" class="nav-link active" data-scroll-target="#studies-that-assessed-reproducibility"><span class="header-section-number">10.1</span> Studies that assessed reproducibility</a>
  <ul class="collapse">
  <li><a href="#summary-of-studies" id="toc-summary-of-studies" class="nav-link" data-scroll-target="#summary-of-studies"><span class="header-section-number">10.1.1</span> Summary of studies</a></li>
  <li><a href="#which-studies-are-most-relevant-how-do-they-compare" id="toc-which-studies-are-most-relevant-how-do-they-compare" class="nav-link" data-scroll-target="#which-studies-are-most-relevant-how-do-they-compare"><span class="header-section-number">10.1.2</span> Which studies are most relevant? How do they compare?</a></li>
  </ul></li>
  <li><a href="#studies-that-evaluated-research-artefacts-andor-articles" id="toc-studies-that-evaluated-research-artefacts-andor-articles" class="nav-link" data-scroll-target="#studies-that-evaluated-research-artefacts-andor-articles"><span class="header-section-number">10.2</span> Studies that evaluated research artefacts and/or articles</a></li>
  <li><a href="#other-relevant-articles-for-introduction-andor-discussion" id="toc-other-relevant-articles-for-introduction-andor-discussion" class="nav-link" data-scroll-target="#other-relevant-articles-for-introduction-andor-discussion"><span class="header-section-number">10.3</span> Other relevant articles for introduction and/or discussion</a></li>
  <li><a href="#journal-procedures" id="toc-journal-procedures" class="nav-link" data-scroll-target="#journal-procedures"><span class="header-section-number">10.4</span> Journal procedures</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">10.5</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../pages/results_discussion.html">Discussion</a></li><li class="breadcrumb-item"><a href="../pages/other_studies.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Comparison to other studies</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Comparison to other studies</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="studies-that-assessed-reproducibility" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="studies-that-assessed-reproducibility"><span class="header-section-number">10.1</span> Studies that assessed reproducibility</h2>
<section id="summary-of-studies" class="level3" data-number="10.1.1">
<h3 data-number="10.1.1" class="anchored" data-anchor-id="summary-of-studies"><span class="header-section-number">10.1.1</span> Summary of studies</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 25%">
<col style="width: 15%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Study</th>
<th>Focus</th>
<th>Articles that tried running code from</th>
<th>Brief summary</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="citation" data-cites="chang_is_2022">Chang and Li (<a href="#ref-chang_is_2022" role="doc-biblioref">2022</a>)</span></td>
<td>Macroeconomics articles</td>
<td>59</td>
<td>Of 67 articles, 6 use confidential data and 2 use software they don’t have, leaving 59. Of those, replicate 22 without author assistance and 29 with. (Note: no access to article - based on abstract).</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="eubank_lessons_2016">Eubank (<a href="#ref-eubank_lessons_2016" role="doc-biblioref">2016</a>)</span></td>
<td>Articles in the Quarterly Journal of Political Science which underwent in-house replication review</td>
<td>24</td>
<td>Of the 24, 4 didn’t require modifications, 13 had code that would run without error, 8 were missing code for results in paper, 7 had no installation directions for dependencies, 14 (58%) had results in paper that differed from code-generated</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="galiani_incentives_2017">Galiani, Gertler, and Romero (<a href="#ref-galiani_incentives_2017" role="doc-biblioref">2017</a>)</span></td>
<td>Economics articles</td>
<td>Unclear</td>
<td>Of 203 included articles, 76% published any data or code. For those that had data and code, 54% of data manipulation code and 61% of “estimation code” could run without major modifications. They found 14% articles fully replicable (raw data to results) and 37% partially (estimated data to results)</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="konkol_computational_2019">Konkol, Kray, and Pfeiffer (<a href="#ref-konkol_computational_2019" role="doc-biblioref">2019</a>)</span></td>
<td>Geoscientific articles</td>
<td>41</td>
<td>Of 41 (R), 2 ran without issue, 33 had resolvable issues, 2 were partially executable, and 4 could not resolve issues. Author assistance for several (e.g.&nbsp;pointing out solutions, sending additional code and data).</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="krafczyk_learning_2021">Krafczyk et al. (<a href="#ref-krafczyk_learning_2021" role="doc-biblioref">2021</a>)</span></td>
<td>Articles from Journal of Computational Physics</td>
<td>7</td>
<td>Attempt to reproduce 7, allow troubleshooting up to 40 hours, success only described via viewing in a figure</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="henderson_reproducibility_2024">Henderson et al. (<a href="#ref-henderson_reproducibility_2024" role="doc-biblioref">2024</a>)</span></td>
<td>Infectious disease models</td>
<td>67</td>
<td>200 (100 random, 100 most highly cited). Not reproducible if properietary software/data inaccessible. For random, 19 had code and data. Of those, 4 completedly reproduced and 8 partially. For highly cited, 48 had code and data. Of those, 11 completely reproduced and 22 partially.</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="mccullough_lessons_2006">McCullough, McGeary, and Harrison (<a href="#ref-mccullough_lessons_2006" role="doc-biblioref">2006</a>)</span></td>
<td>Articles from Journal of Money, Credit and Banking</td>
<td>58</td>
<td>Of 266 articles, 193 should have archive entries, but only 69 did. Of those 69, should have code and data, but found only data for 11 of them (i.e.&nbsp;no code). Attempted to use supplied data and code of remaining 58 to reproduce published results. Allowed minor troubleshooting.</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="obels_analysis_2020">Obels et al. (<a href="#ref-obels_analysis_2020" role="doc-biblioref">2020</a>)</span></td>
<td>Registered Reports in psychology</td>
<td>36</td>
<td>Of 62 articles, 36 had data and code. Could run 31 and reproduced main results for 21.</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="samuel_computational_2024">Samuel and Mietchen (<a href="#ref-samuel_computational_2024" role="doc-biblioref">2024</a>)</span></td>
<td>Jupyter notebooks associated with publications</td>
<td>15,817</td>
<td>3467 publications, from which 27,271 jupyter notebooks were downloaded for further analysis. Of those, 22,578 were Python and 15,817 had dependencies declared in standard file. Attempted to re-run those automatically. 10,388 installed dependencies successfully. Of those, 1203 ran without error - and then 879 had results identical to original, 324 differed</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="stagge_assessing_2019">Stagge et al. (<a href="#ref-stagge_assessing_2019" role="doc-biblioref">2019</a>)</span></td>
<td>Hydrology and water resources articles</td>
<td>20</td>
<td>Looked at data, model and code availability in 360 articles. Of those, 20 had required data/code/directions available for reproduction. Fully reproduce 4, partially reproduced 2, couldn’t reproduce 2, and found 10 actually didn’t have all the required artefacts. Allowed minor troubleshooting (e.g.&nbsp;folder/file locations)</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="stockemer_data_2018">Stockemer, Koehler, and Lentz (<a href="#ref-stockemer_data_2018" role="doc-biblioref">2018</a>)</span></td>
<td>Political science articles</td>
<td>71</td>
<td>Looked for data/code in 145 articles, then emailed authors to ask for it. Received data and code for 71. For those, ran code, and success in reproducing apx. 70%.</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="stodden_enabling_2018">Stodden, Krafczyk, and Bhaskar (<a href="#ref-stodden_enabling_2018" role="doc-biblioref">2018</a>)</span></td>
<td>Articles from Journal of Computational Physics</td>
<td>55</td>
<td>Precursor to <span class="citation" data-cites="krafczyk_learning_2021">Krafczyk et al. (<a href="#ref-krafczyk_learning_2021" role="doc-biblioref">2021</a>)</span>. Of 306 articles, 55 had code. Spent max 4 hours on them, managed to reproduce some struff for 18, but didn’t complete any.</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="stodden_empirical_2018">Stodden, Seiler, and Ma (<a href="#ref-stodden_empirical_2018" role="doc-biblioref">2018</a>)</span></td>
<td>Articles from Science before and after policy change around code sharing</td>
<td>22</td>
<td>After policy was 204 articles - could identify artefacts themselves for 24, but contacted authors for 180, of which 131 replied - of which got data/code for 65/180 (36%). From looking at the then total of 89 article artefacts, anticipated 56 to looked potentially reproducible. Chose 22 of them and were able to replicate results in publication for all except one (large dataset and software no longer acccesible). Issues in those thought not to reproduce were missing scripts, documentation, or parameters. Few papers cited visualisation tools, even when visualisation in article were important.</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="wood_push_2018">Wood, Müller, and Brown (<a href="#ref-wood_push_2018" role="doc-biblioref">2018</a>)</span></td>
<td>Impact evaluations in low- and middle-income countries</td>
<td>50</td>
<td>Of 109, 27 ran to produced comparable results. 59 refused to provide replications files. Of remaining 23, 3 had propreitrary data, 15 had incomplete replication files, and 5 had minor differences in results.</td>
</tr>
</tbody>
</table>
<p>Examples that just try and run code but don’t check results:</p>
<ul>
<li><span class="citation" data-cites="trisovic_large-scale_2022">Trisovic et al. (<a href="#ref-trisovic_large-scale_2022" role="doc-biblioref">2022</a>)</span> - R code from the Harvard Dataverse repository | 9000 unique R files from 2000+ replication packages - with interesting oobservations about basic code cleaning, whether there’s documentation and comments, and some stuff about <strong>backwards compatability of R</strong> and how it does become non-compatabile</li>
</ul>
<p>Examples that use code and/or description in article (i.e.&nbsp;dont’ <em>require</em> code):</p>
<ul>
<li><span class="citation" data-cites="laurinavichyute_share_2022">Laurinavichyute, Yadav, and Vasishth (<a href="#ref-laurinavichyute_share_2022" role="doc-biblioref">2022</a>)</span> - Articles in the Journal of Memory and Language - Look at data sharing in 59 articles before and 59 articles after a policy is in place. For the 59 after policy, attempted to reproduced. 8 had inaccessible data. Under strict criteria, reproduced 20 (34%). Under lenient criteria, 33 (56%).</li>
<li><span class="citation" data-cites="hardwicke_data_2018">Hardwicke et al. (<a href="#ref-hardwicke_data_2018" role="doc-biblioref">2018</a>)</span> - 35 articles, two team members attempted for each article, used available data and information in article or any other additional documentation</li>
<li><span class="citation" data-cites="hardwicke_analytic_2021">Hardwicke et al. (<a href="#ref-hardwicke_analytic_2021" role="doc-biblioref">2021</a>)</span> - Articles in Psychological Science - 25 evaluated - initially 16 had at least one “major numerical discprenancy”, after troubleshooting with/without authors, 37 discrepancnies remained from 789 checked values</li>
<li><span class="citation" data-cites="ostermann_advancing_2017">Ostermann and Granell (<a href="#ref-ostermann_advancing_2017" role="doc-biblioref">2017</a>)</span> - reproducibility required full data set + executable tools or precise step-by-step instructions</li>
</ul>
<p>Examples that reuses data and repeats analysis “exactly as described in report” with clarification if needed:</p>
<ul>
<li><span class="citation" data-cites="schwander_replication_2021">Schwander et al. (<a href="#ref-schwander_replication_2021" role="doc-biblioref">2021</a>)</span> - 4 health economic obesity models</li>
<li><span class="citation" data-cites="naudet_data_2018">Naudet et al. (<a href="#ref-naudet_data_2018" role="doc-biblioref">2018</a>)</span></li>
<li><span class="citation" data-cites="raff_step_2019">Raff (<a href="#ref-raff_step_2019" role="doc-biblioref">2019</a>)</span></li>
<li><span class="citation" data-cites="artner_reproducibility_2021">Artner et al. (<a href="#ref-artner_reproducibility_2021" role="doc-biblioref">2021</a>)</span></li>
<li><span class="citation" data-cites="maassen_reproducibility_2020">Maassen et al. (<a href="#ref-maassen_reproducibility_2020" role="doc-biblioref">2020</a>)</span></li>
</ul>
</section>
<section id="which-studies-are-most-relevant-how-do-they-compare" class="level3" data-number="10.1.2">
<h3 data-number="10.1.2" class="anchored" data-anchor-id="which-studies-are-most-relevant-how-do-they-compare"><span class="header-section-number">10.1.2</span> Which studies are most relevant? How do they compare?</h3>
<p>Note: It is difficult to make comparisons between all these studies due to the large variation in methods (such as amount of troubleshooting allowed, or thresholds for deciding something is reproduced). As such, the actual percentage reproduced is difficult to compare.</p>
<p>However, this section does try to pull out the more relevant studies (in terms of their focus and/or methods), and consider the <strong>similarities and differences</strong> to our work (e.g.&nbsp;broadly considering reproduction findings, but focusing particularly on <strong>issues encountered</strong> and <strong>recommendations made</strong>).</p>
<!--TODO: Write this section -->
<p><strong>Similar focus</strong>: <span class="citation" data-cites="henderson_reproducibility_2024">Henderson et al. (<a href="#ref-henderson_reproducibility_2024" role="doc-biblioref">2024</a>)</span></p>
<ul>
<li>Infectious disease models (i.e.&nbsp;models, health)</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Some old rough notes
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><span class="citation" data-cites="krafczyk_learning_2021">Krafczyk et al. (<a href="#ref-krafczyk_learning_2021" role="doc-biblioref">2021</a>)</span> - results are recommendations based on experiences, which were:
<ul>
<li>can see completion in figure 1, but focus is very much on the learnings rather than % reproduced and so on</li>
<li>being clear on links between article, code and data (e.g.&nbsp;which code uses which data, and which parts of code made each bit of article)</li>
<li>include scripts for each aspect of article, with it easy to locate the scripts needed, and the scripts including the parameters needed and clearly label</li>
<li>be clear about hardware needed, e.g.&nbsp;if large amount of computing resources would be required. at least report hardware used. ideally include “small test case that can be run by users with conventional hardware”</li>
<li>list software dependencies and versions</li>
<li>use seeds, and report seed you used</li>
<li>make all code and data available with an appropriate licence</li>
<li>include master script that runs in computations in publication</li>
<li>use same terminology in code and article</li>
<li>use version control and specify the e.g.&nbsp;commit hash that identifies the version used</li>
<li>avoid hard coding parameters</li>
<li>design scripts in a way that allows people to easily change parameters and run again</li>
<li>avoid hard coding file paths</li>
<li>provide script that checks whether users results match original (within expected deviation)</li>
<li>if compare against competing methods, include info on how those were implemented and tested</li>
<li>use build system for C/C++ code</li>
<li>provide scripts to make the figures and tables</li>
</ul></li>
<li><span class="citation" data-cites="wood_push_2018">Wood, Müller, and Brown (<a href="#ref-wood_push_2018" role="doc-biblioref">2018</a>)</span>
<ul>
<li>complete data: 27 comparable results, 5 minor differences, 0 major differences</li>
<li>incomplete data: 10 comparable, 4 minor differences, 1 major differences</li>
<li>main issue was the code and data not being shared</li>
</ul></li>
<li><span class="citation" data-cites="schwander_replication_2021">Schwander et al. (<a href="#ref-schwander_replication_2021" role="doc-biblioref">2021</a>)</span>
<ul>
<li>reproduction success for 3 out of 4 models</li>
<li>facilitators:
<ul>
<li>“Model structure and possible state transitions were presented in a state transition diagram”</li>
<li>“Overview of input parameters was provided in table format”</li>
</ul></li>
<li>hurdles:
<ul>
<li>“PSAs were performed” (probablistic sensitivity analysis)</li>
<li>“Relevant PSA values for PSA result reproduction were provided (type of distribution and either mean and standard deviation or distribution parameters were provided)”</li>
<li>“Clinical event simulation results were provided (which are very helpful to guide potential assumptions to be made for rebuilding the model and which provide an additional means of testing the fit of the replication)”</li>
<li>“Relevant details on the underlying life tables were provided (including year of data)”</li>
<li>“Several self-created regression equations were introduced but without details on how to apply/solve the provided regressions correctly”</li>
</ul></li>
<li>“We <strong>investigated whether the CHEERS score might be predictive for the success of model replication</strong>, but this was not the case, with scores ranging from 18 to 20. The non-successful replication case study 1 rated a score of 19 (the maximum possible CHEERS score is 24). A <strong>comparable finding was observed by another research team that investigated the Phillips checklist</strong> [24] in the context of model replication; they found that the Phillips checklist was not reliable for ensuring that studies are replicable [2].” They then <strong>propose changes</strong> to CHEERS that might help with replicability</li>
</ul></li>
<li><span class="citation" data-cites="henderson_reproducibility_2024">Henderson et al. (<a href="#ref-henderson_reproducibility_2024" role="doc-biblioref">2024</a>)</span></li>
<li><span class="citation" data-cites="samuel_computational_2024">Samuel and Mietchen (<a href="#ref-samuel_computational_2024" role="doc-biblioref">2024</a>)</span>
<ul>
<li>Reproduction success:
<ul>
<li>27,271 jupyter notebooks (2660 GitHub repositories, 3467 publications, majority python)</li>
<li>15,817 included dependencies in standard requirement files</li>
<li>Of those, 10,388 could be installed successfully</li>
<li>Of those, 1203 ran without error</li>
<li>Of those, 879 produced results identical to those reported in the original notebook</li>
</ul></li>
<li>References several other studies that have attempted to re-run jupyter notebooks</li>
<li>ModuleNotFoundError, ImportError and FileNotFounderError were the top 3 common exceptions</li>
<li>Also used <code>flakenb</code> to look for code styling errors</li>
<li>Implications:
<ul>
<li>Low reproducibility as in prior studies</li>
<li>Review processes don’t pay attention to journal reproducibiltiy</li>
<li>Common errors around dependencies… Use exiting approaches like requirements, conda and poetry</li>
<li>Some journals, article types, levels of documentation and research fields had more reproduced notebooks than others. Worth considering procedures at those journals with most reproduced (<strong>iScience</strong>). Also, notebooks combining computation and narrative.</li>
<li>Things go out of data… importance of pre-prints…</li>
<li>Reproducibility badges, reproducibility platforms like REScience, nanopublications</li>
</ul></li>
</ul></li>
</ul>
</div>
</div>
</div>
</section>
</section>
<section id="studies-that-evaluated-research-artefacts-andor-articles" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="studies-that-evaluated-research-artefacts-andor-articles"><span class="header-section-number">10.2</span> Studies that evaluated research artefacts and/or articles</h2>
<!--TODO: Look into this -->
<p>e.g. <span class="citation" data-cites="schwander_replication_2021">Schwander et al. (<a href="#ref-schwander_replication_2021" role="doc-biblioref">2021</a>)</span> and <span class="citation" data-cites="zhang_reporting_2020">Zhang, Lhachimi, and Rogowski (<a href="#ref-zhang_reporting_2020" role="doc-biblioref">2020</a>)</span> for reporting… <span class="citation" data-cites="laurinavichyute_share_2022">Laurinavichyute, Yadav, and Vasishth (<a href="#ref-laurinavichyute_share_2022" role="doc-biblioref">2022</a>)</span> for code…</p>
</section>
<section id="other-relevant-articles-for-introduction-andor-discussion" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="other-relevant-articles-for-introduction-andor-discussion"><span class="header-section-number">10.3</span> Other relevant articles for introduction and/or discussion</h2>
<ul>
<li><span class="citation" data-cites="monks_computer_2023">Monks and Harper (<a href="#ref-monks_computer_2023" role="doc-biblioref">2023</a>)</span> - see summary in <strong>introduction</strong></li>
<li><span class="citation" data-cites="hrynaszkiewicz_survey_2021">Hrynaszkiewicz, Harney, and Cadwallader (<a href="#ref-hrynaszkiewicz_survey_2021" role="doc-biblioref">2021</a>)</span>
<ul>
<li>Survey in Autumn 2020 of previous authors and other registered users with PLOS Computational Biology</li>
<li>214 complete responses</li>
<li>Lots had papers where code was not shared - reasons inc (1) takes too much time to prepare code for sharing, (2) software and systems dependencies (3) concerns with my ability to prepare the code for sharing (4) I needed to protect intellectual property, etc…</li>
<li>More likely to submit to journal if mandatory code sharing policy (moreso for ECR)</li>
<li>Low mean satisfication score for accessing others code (44.0)</li>
</ul></li>
<li><span class="citation" data-cites="cadwallader_survey_2022">Cadwallader and Hrynaszkiewicz (<a href="#ref-cadwallader_survey_2022" role="doc-biblioref">2022</a>)</span>
<ul>
<li>Survey in Spring 2021 of previous authors and other registers used with PLOS computational biology related disciplines</li>
<li>188 complete responses</li>
<li>Questions on
<ul>
<li>How often look at code associated with research articles</li>
<li>Whether have encountered different methods of code sharing</li>
<li>How useful found different methods of accessing code - <strong>link to code repository was rated most useful - with code “available upon request” least useful</strong>. When explaining why link was most useful, common reasons were: (<strong>a) ability to see new versions of code (b) quick access to code (c) good documentation/README (d) practicality (e) reproduction of results (f) established</strong>. For sharing via notebooks, like ability to explore code and reproduction of results. For archived code, like that it gives long term access.</li>
<li>Features of code notebooks that are useful when accessing/reading code, highest ranked: (1) having all code, data and figures in one place, (2) knowing code is running in right environment (3) ability to interact inline with code in browser (4) ability to uncover data point by hovering over point in graph …etc</li>
<li>Satisifcation and importance scores of factors associated with sharing code</li>
<li>Time spent preparing and sharing code</li>
<li>Extra time willing to spend to make code easier to read and run</li>
</ul></li>
</ul></li>
<li><span class="citation" data-cites="noauthor_revisiting_2022"><span>“Revisiting Code Reusability”</span> (<a href="#ref-noauthor_revisiting_2022" role="doc-biblioref">2022</a>)</span>
<ul>
<li>Initiative from Nature Machine Intelligence to have new article type <strong>“Reusability Report”</strong> where researchers try code from article in journal and try running it, applying to new data or tweaking or extending it</li>
</ul></li>
<li><span class="citation" data-cites="mejba_evolution_2023">Mejba et al. (<a href="#ref-mejba_evolution_2023" role="doc-biblioref">2023</a>)</span>
<ul>
<li>Lists <strong>benefits of code reuse</strong>: increase <strong>productivity</strong>, improved code quality, reduced errors, cost efficiency, faster time-to-market, <strong>knowledge sharing</strong>, scalability, sustainability, innovation</li>
<li>Lists challenges of code reuse: <strong>understanding reused code</strong>, integration issues, incompatability, maintaining and updating reused code, <strong>licensing and ownership</strong>, security risks, quality control, overhead, dependency management</li>
<li>Gives solutions to changes e.g.&nbsp;understanding reused code –&gt; <strong>comprehensive documentation</strong></li>
<li>Strategies for effective code reuse… modular design, use of libraries and frameworks, design patterns, object oriented programming, apis and microservices, code documentation, automated testing, refactoring, code reviews, ci/cd</li>
<li>Lists security implications of code reuse, and best practices for security</li>
<li>Impacts of code reuse on software development lifecycle:
<ul>
<li>Planning and analysis - <strong>reuse code can reduce time and resources required, although crucial to check code compatability, quality and security to meet needs</strong></li>
<li>Design - design of code can facilitate reuse</li>
<li>Implementation - reuse snippets, lirbaries, etc.</li>
<li>Testing - reused code can have benefit of being previously tests so less bugs, more stable software, but will need rigorous re test</li>
<li>Deployment - if code has depenedencies, need to manage properly eg docker</li>
<li>Maintenance - if reused code well understood and well documentation can make maintence easier</li>
</ul></li>
</ul></li>
<li><span class="citation" data-cites="dupre_beyond_2022">DuPre et al. (<a href="#ref-dupre_beyond_2022" role="doc-biblioref">2022</a>)</span>
<ul>
<li><a href="https://theplosblog.plos.org/2022/05/uphold-the-code/" class="uri">https://theplosblog.plos.org/2022/05/uphold-the-code/</a> describes the article, saying ” DuPree and colleagues draw a distinction between the scholarly article, which they argue functions as a kind of preview or entrypoint to the research, and the real scholarly work. That is, the methods researchers develop (in this case software and code), and the data they gather and analyze in order to produce a result. It’s this data and code which forms the core of the research, the fulcrum on which everything else turns. For that reason, code not only deserves a place in the literature, it is required in order to fully understand and appreciate the scholarship.”</li>
<li>Article is about “<strong>hybrid research objects</strong>” - i.e.&nbsp;multiple content types, so narrative text plus at least one of: code, data, and/or computation. Can link in data/code availability statements. Publisher may require those linked objects to meet specific standards and include as part of review process. “Hope to see more hybrid research objects where each linked object is formatted with domain-relevant standards… and bi-directionally linked using persistent identifiers”</li>
<li>Article then talks about interactive research objects, with everything all in one place, like “executable research articles”, RMarkdown, Jupyter Book, Binder, Pangeo, NeuroLibre</li>
</ul></li>
<li><span class="citation" data-cites="benureau_re-run_2018">Benureau and Rougier (<a href="#ref-benureau_re-run_2018" role="doc-biblioref">2018</a>)</span>
<ul>
<li>They use terms from <strong>Goble 2016</strong>. They then show a simple python example which they progressively modify to meet these criteria. <strong>Really nice paper! Could be good in introduction and elsewhere?</strong>
<ul>
<li><strong>R1: Re-runnable</strong> (executable)
<ul>
<li>“it is impossible to write future-proof code… modernizing an unmaintained ten-year-old code can reveal itself to be an arduous and expensive undertaking—and precarious… more straightforward solution is to recreate the old execution environment. For this to happen however, the dependencies in terms of systems, software, and libraries must be made clear enough.”</li>
</ul></li>
<li><strong>R2: Repeatable</strong> (produce the same result more than once)
<ul>
<li>“it often comes down to controlling the initialization of the pseudo-random number generators (RNG).” –&gt; <strong>importance of seeds</strong></li>
</ul></li>
<li><strong>R3: Reproducible</strong> (allow an investigator to reobtain published results)
<ul>
<li>Explicit dependencies and operating system</li>
<li>“includes pre-processing, post-processing, and plotting code”</li>
<li>good practice to include short unit tests that verify reproduction</li>
<li>code and input data and result data should all be made available</li>
</ul></li>
<li><strong>R4: Reusable</strong> (easy to use, understand and modify)
<ul>
<li>comments and documentation</li>
<li>“reusability can represent an expensive endeavor if undertaken as an afterthought”</li>
<li>simple things that improve reusability:
<ul>
<li>avoid hardcoded values or magic numbers</li>
<li>changes to code behaviour should be via modifiable parameters rather than commenting/uncommenting - so (a) conditions are recorded as parameters, and (b) can have seperate scripts to run and produce results</li>
</ul></li>
</ul></li>
<li><strong>R5: Replicable</strong> (“act as an available reference for any ambiguity in the algorithmic descriptions of the article”)
<ul>
<li>“replicating implies writing a new code matching the conceptual description of the article, in order to reobtain the same result”</li>
<li>whilst this relies on the article, you will inveitably have ambiguities in the article, and so “Replication efforts use the paper first, and then the reproducible code that comes along with it whenever the paper falls short of being precise enough.”</li>
</ul></li>
</ul></li>
<li>“In conclusion, the R3 <strong>(reproducible) form should be accepted as the minimum scientific standard</strong> (Wilson et al., 2017).”</li>
</ul></li>
<li><span class="citation" data-cites="wilson_good_2017">Wilson et al. (<a href="#ref-wilson_good_2017" role="doc-biblioref">2017</a>)</span>
<ul>
<li>Supplements the “<strong>Best Practices for Scientific Computing” article</strong> by giving a minimum set of”<strong>good enough</strong>” things to do</li>
<li>Box 1 summarises the practices which are grouped into:
<ul>
<li>Data management (e.g.&nbsp;saving data, documenting steps, tidy data)</li>
<li>Software (eg. writing organising sharing scripts)</li>
<li>Collaboration (eg. make it easier for collaborators to understand and contribute)</li>
<li>Project organisation (eg. organise artefacts to ease discvoery and understanding)</li>
<li>Tracking changes (i.e.&nbsp;record how components of project change over time)</li>
<li>Manuscripts (eg. write manuscript with audit trail - so either history/change tracking, or version control)</li>
</ul></li>
</ul></li>
<li><span class="citation" data-cites="gomes_why_2022">Gomes et al. (<a href="#ref-gomes_why_2022" role="doc-biblioref">2022</a>)</span>
<ul>
<li><strong>Figure 1</strong> is a nice</li>
<li><strong>Barriers</strong>
<ul>
<li>Knowledge barriers - unsure about process, complex or manual workflows, large data files, insecurity, do not see value</li>
<li>Reuse concerns - inappropriate use, rights, sensitive content, transient storage</li>
<li>Disincentives - scooping, lack of time, lack of incentives</li>
</ul></li>
</ul></li>
<li><span class="citation" data-cites="connolly_software_2023">Connolly et al. (<a href="#ref-connolly_software_2023" role="doc-biblioref">2023</a>)</span>
<ul>
<li>3Rs of software enginerring: “readability (human understandable codes), resilience (fails rarely/gracefully), and reuse (can easily be used by others and can be embedded in other software)”</li>
<li>Walks through some practices… version control, software design, computer programming or coding, quality assurance, packaging and deployment, user documentation, team management, user engagement</li>
</ul></li>
<li><span class="citation" data-cites="eglen_toward_2017">Eglen et al. (<a href="#ref-eglen_toward_2017" role="doc-biblioref">2017</a>)</span>
<ul>
<li>Simple guidelines for code sharing: version control, persistent URLs, license, etiquette, documentation, tools, case studies, data, standards, tests, user supoprt</li>
<li>Tests - “We recommend including <strong>test suites demonstrating that the code is producing the correct results</strong>37. These tests can be at a low level (testing each individual function, called unit testing) or at a higher level (for example, testing that the program yields correct answers on simulated data)38.” - and can link with <strong>continuous integration</strong> so automatically run and fail if change made to code that fails it</li>
</ul></li>
<li><span class="citation" data-cites="gil_toward_2016">Gil et al. (<a href="#ref-gil_toward_2016" role="doc-biblioref">2016</a>)</span>
<ul>
<li>Proposed checklits for things to include in paper, grouped into categories of:
<ul>
<li>Data accessibility</li>
<li>Data documentation</li>
<li>Software accessibility</li>
<li>Software documentation</li>
<li>Provenance documentation</li>
<li>Methods documentation</li>
<li>Authors identification</li>
</ul></li>
<li>Suggest papers enriched with metadata/artefacts</li>
</ul></li>
</ul>
</section>
<section id="journal-procedures" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="journal-procedures"><span class="header-section-number">10.4</span> Journal procedures</h2>
<!--TODO: Finish this -->
<p><em>Psychological Science</em></p>
<p><em>Quarterly Journal of Political Science</em> in-house replication review - <span class="citation" data-cites="eubank_lessons_2016">Eubank (<a href="#ref-eubank_lessons_2016" role="doc-biblioref">2016</a>)</span></p>
<p><em>Cortex</em> Verification Reports - <span class="citation" data-cites="chambers_verification_2020">Chambers (<a href="#ref-chambers_verification_2020" role="doc-biblioref">2020</a>)</span></p>
<p><span class="citation" data-cites="galiani_incentives_2017">Galiani, Gertler, and Romero (<a href="#ref-galiani_incentives_2017" role="doc-biblioref">2017</a>)</span> surveys journals about policies on sharing data and code</p>
<p>Journal of Memory and Language - open data and code policy, requiring code and data to be released</p>
<p>Vadose Zone Journal - “Reproducible Research” programme where code and data is published alongside article - <span class="citation" data-cites="skaggs_reproducible_2015">Skaggs, Young, and Vrugt (<a href="#ref-skaggs_reproducible_2015" role="doc-biblioref">2015</a>)</span></p>
</section>
<section id="references" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="references"><span class="header-section-number">10.5</span> References</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-artner_reproducibility_2021" class="csl-entry" role="listitem">
Artner, Richard, Thomas Verliefde, Sara Steegen, Sara Gomes, Frits Traets, Francis Tuerlinckx, and Wolf Vanpaemel. 2021. <span>“The Reproducibility of Statistical Results in Psychological Research: <span>An</span> Investigation Using Unpublished Raw Data.”</span> <em>Psychological Methods</em> 26 (5): 527–46. <a href="https://doi.org/10.1037/met0000365">https://doi.org/10.1037/met0000365</a>.
</div>
<div id="ref-benureau_re-run_2018" class="csl-entry" role="listitem">
Benureau, Fabien C. Y., and Nicolas P. Rougier. 2018. <span>“Re-Run, <span>Repeat</span>, <span>Reproduce</span>, <span>Reuse</span>, <span>Replicate</span>: <span>Transforming</span> <span>Code</span> into <span>Scientific</span> <span>Contributions</span>.”</span> <em>Frontiers in Neuroinformatics</em> 11 (January). <a href="https://doi.org/10.3389/fninf.2017.00069">https://doi.org/10.3389/fninf.2017.00069</a>.
</div>
<div id="ref-cadwallader_survey_2022" class="csl-entry" role="listitem">
Cadwallader, Lauren, and Iain Hrynaszkiewicz. 2022. <span>“A Survey of Researchers’ Code Sharing and Code Reuse Practices, and Assessment of Interactive Notebook Prototypes.”</span> <em>PeerJ</em> 10 (August): e13933. <a href="https://doi.org/10.7717/peerj.13933">https://doi.org/10.7717/peerj.13933</a>.
</div>
<div id="ref-chambers_verification_2020" class="csl-entry" role="listitem">
Chambers, Christopher D. 2020. <span>“<em><span>Verification</span> <span>Reports</span></em>: <span>A</span> New Article Type at <em>Cortex</em>.”</span> <em>Cortex</em> 129 (August): A1–3. <a href="https://doi.org/10.1016/j.cortex.2020.04.020">https://doi.org/10.1016/j.cortex.2020.04.020</a>.
</div>
<div id="ref-chang_is_2022" class="csl-entry" role="listitem">
Chang, Andrew, and Phillip Li. 2022. <span>“Is <span>Economics</span> <span>Research</span> <span>Replicable</span>? <span>Sixty</span> <span>Published</span> <span>Papers</span> <span>From</span> <span>Thirteen</span> <span>Journals</span> <span>Say</span> <span>‘<span>Often</span> <span>Not</span>’</span>.”</span> <em>Critical Finance Review</em> 11 (1): 185–206. <a href="https://doi.org/10.1561/104.00000053">https://doi.org/10.1561/104.00000053</a>.
</div>
<div id="ref-connolly_software_2023" class="csl-entry" role="listitem">
Connolly, Andrew, Joseph Hellerstein, Naomi Alterman, David Beck, Rob Fatland, Ed Lazowska, Vani Mandava, and Sarah Stone. 2023. <span>“Software <span>Engineering</span> <span>Practices</span> in <span>Academia</span>: <span>Promoting</span> the <span>3Rs</span>—<span>Readability</span>, <span>Resilience</span>, and <span>Reuse</span>.”</span> <em>Harvard Data Science Review</em> 5 (2). <a href="https://doi.org/10.1162/99608f92.018bf012">https://doi.org/10.1162/99608f92.018bf012</a>.
</div>
<div id="ref-dupre_beyond_2022" class="csl-entry" role="listitem">
DuPre, Elizabeth, Chris Holdgraf, Agah Karakuzu, Loïc Tetrel, Pierre Bellec, Nikola Stikov, and Jean-Baptiste Poline. 2022. <span>“Beyond Advertising: <span>New</span> Infrastructures for Publishing Integrated Research Objects.”</span> <em>PLOS Computational Biology</em> 18 (1): e1009651. <a href="https://doi.org/10.1371/journal.pcbi.1009651">https://doi.org/10.1371/journal.pcbi.1009651</a>.
</div>
<div id="ref-eglen_toward_2017" class="csl-entry" role="listitem">
Eglen, Stephen J., Ben Marwick, Yaroslav O. Halchenko, Michael Hanke, Shoaib Sufi, Padraig Gleeson, R. Angus Silver, et al. 2017. <span>“Toward Standard Practices for Sharing Computer Code and Programs in Neuroscience.”</span> <em>Nature Neuroscience</em> 20 (6): 770–73. <a href="https://doi.org/10.1038/nn.4550">https://doi.org/10.1038/nn.4550</a>.
</div>
<div id="ref-eubank_lessons_2016" class="csl-entry" role="listitem">
Eubank, Nicholas. 2016. <span>“Lessons from a <span>Decade</span> of <span>Replications</span> at the <span>Quarterly</span> <span>Journal</span> of <span>Political</span> <span>Science</span>.”</span> <em>PS: Political Science &amp; Politics</em> 49 (2): 273–76. <a href="https://doi.org/10.1017/S1049096516000196">https://doi.org/10.1017/S1049096516000196</a>.
</div>
<div id="ref-galiani_incentives_2017" class="csl-entry" role="listitem">
Galiani, Sebastian, Paul Gertler, and Mauricio Romero. 2017. <span>“Incentives for <span>Replication</span> in <span>Economics</span>.”</span> Working {Paper}. Working <span>Paper</span> <span>Series</span>. National Bureau of Economic Research. <a href="https://doi.org/10.3386/w23576">https://doi.org/10.3386/w23576</a>.
</div>
<div id="ref-gil_toward_2016" class="csl-entry" role="listitem">
Gil, Yolanda, Cédric H. David, Ibrahim Demir, Bakinam T. Essawy, Robinson W. Fulweiler, Jonathan L. Goodall, Leif Karlstrom, et al. 2016. <span>“Toward the <span>Geoscience</span> <span>Paper</span> of the <span>Future</span>: <span>Best</span> Practices for Documenting and Sharing Research from Data to Software to Provenance.”</span> <em>Earth and Space Science</em> 3 (10): 388–415. <a href="https://doi.org/10.1002/2015EA000136">https://doi.org/10.1002/2015EA000136</a>.
</div>
<div id="ref-gomes_why_2022" class="csl-entry" role="listitem">
Gomes, Dylan G. E., Patrice Pottier, Robert Crystal-Ornelas, Emma J. Hudgins, Vivienne Foroughirad, Luna L. Sánchez-Reyes, Rachel Turba, et al. 2022. <span>“Why Don’t We Share Data and Code? <span>Perceived</span> Barriers and Benefits to Public Archiving Practices.”</span> <em>Proceedings of the Royal Society B: Biological Sciences</em> 289 (1987): 20221113. <a href="https://doi.org/10.1098/rspb.2022.1113">https://doi.org/10.1098/rspb.2022.1113</a>.
</div>
<div id="ref-hardwicke_analytic_2021" class="csl-entry" role="listitem">
Hardwicke, Tom E., Manuel Bohn, Kyle MacDonald, Emily Hembacher, Michèle B. Nuijten, Benjamin N. Peloquin, Benjamin E. deMayo, Bria Long, Erica J. Yoon, and Michael C. Frank. 2021. <span>“Analytic Reproducibility in Articles Receiving Open Data Badges at the Journal <span>Psychological</span> <span>Science</span>: An Observational Study.”</span> <em>Royal Society Open Science</em> 8 (1): 201494. <a href="https://doi.org/10.1098/rsos.201494">https://doi.org/10.1098/rsos.201494</a>.
</div>
<div id="ref-hardwicke_data_2018" class="csl-entry" role="listitem">
Hardwicke, Tom E., Maya B. Mathur, Kyle MacDonald, Gustav Nilsonne, George C. Banks, Mallory C. Kidwell, Alicia Hofelich Mohr, et al. 2018. <span>“Data Availability, Reusability, and Analytic Reproducibility: Evaluating the Impact of a Mandatory Open Data Policy at the Journal <span>Cognition</span>.”</span> <em>Royal Society Open Science</em> 5 (8): 180448. <a href="https://doi.org/10.1098/rsos.180448">https://doi.org/10.1098/rsos.180448</a>.
</div>
<div id="ref-henderson_reproducibility_2024" class="csl-entry" role="listitem">
Henderson, Alec S., Roslyn I. Hickson, Morgan Furlong, Emma S. McBryde, and Michael T. Meehan. 2024. <span>“Reproducibility of <span>COVID</span>-Era Infectious Disease Models.”</span> <em>Epidemics</em> 46 (March): 100743. <a href="https://doi.org/10.1016/j.epidem.2024.100743">https://doi.org/10.1016/j.epidem.2024.100743</a>.
</div>
<div id="ref-hrynaszkiewicz_survey_2021" class="csl-entry" role="listitem">
Hrynaszkiewicz, Iain, James Harney, and Lauren Cadwallader. 2021. <span>“A Survey of Code Sharing Practice and Policy in Computational Biology.”</span> OSF. <a href="https://doi.org/10.31219/osf.io/f73a6">https://doi.org/10.31219/osf.io/f73a6</a>.
</div>
<div id="ref-konkol_computational_2019" class="csl-entry" role="listitem">
Konkol, Markus, Christian Kray, and Max Pfeiffer. 2019. <span>“Computational Reproducibility in Geoscientific Papers: <span>Insights</span> from a Series of Studies with Geoscientists and a Reproduction Study.”</span> <em>International Journal of Geographical Information Science</em> 33 (2): 408–29. <a href="https://doi.org/10.1080/13658816.2018.1508687">https://doi.org/10.1080/13658816.2018.1508687</a>.
</div>
<div id="ref-krafczyk_learning_2021" class="csl-entry" role="listitem">
Krafczyk, M. S., A. Shi, A. Bhaskar, D. Marinov, and V. Stodden. 2021. <span>“Learning from Reproducing Computational Results: Introducing Three Principles and the <span>Reproduction</span> <span>Package</span>.”</span> <em>Philosophical Transactions of the Royal Society A: Mathematical, Physical and Engineering Sciences</em> 379 (2197): 20200069. <a href="https://doi.org/10.1098/rsta.2020.0069">https://doi.org/10.1098/rsta.2020.0069</a>.
</div>
<div id="ref-laurinavichyute_share_2022" class="csl-entry" role="listitem">
Laurinavichyute, Anna, Himanshu Yadav, and Shravan Vasishth. 2022. <span>“Share the Code, Not Just the Data: <span>A</span> Case Study of the Reproducibility of Articles Published in the <span>Journal</span> of <span>Memory</span> and <span>Language</span> Under the Open Data Policy.”</span> <em>Journal of Memory and Language</em> 125 (August): 104332. <a href="https://doi.org/10.1016/j.jml.2022.104332">https://doi.org/10.1016/j.jml.2022.104332</a>.
</div>
<div id="ref-maassen_reproducibility_2020" class="csl-entry" role="listitem">
Maassen, Esther, Marcel A. L. M. van Assen, Michèle B. Nuijten, Anton Olsson-Collentine, and Jelte M. Wicherts. 2020. <span>“Reproducibility of Individual Effect Sizes in Meta-Analyses in Psychology.”</span> <em>PLOS ONE</em> 15 (5): e0233107. <a href="https://doi.org/10.1371/journal.pone.0233107">https://doi.org/10.1371/journal.pone.0233107</a>.
</div>
<div id="ref-mccullough_lessons_2006" class="csl-entry" role="listitem">
McCullough, B. D., Kerry Anne McGeary, and Teresa D. Harrison. 2006. <span>“Lessons from the <span>JMCB</span> <span>Archive</span>.”</span> <em>Journal of Money, Credit and Banking</em> 38 (4): 1093–1107. <a href="https://www.jstor.org/stable/3838995">https://www.jstor.org/stable/3838995</a>.
</div>
<div id="ref-mejba_evolution_2023" class="csl-entry" role="listitem">
Mejba, Raoha Bin, Sabbir Morshed Miazi, Ashikur Rahaman Palash, Touhidur Rahman Sobuz, and Ranasinghe Arachchige Tharindu Harshana Ranasinghe. 2023. <span>“The <span>Evolution</span> and <span>Impact</span> of <span>Code</span> <span>Reuse</span>: <span>A</span> <span>Deep</span> <span>Dive</span> into <span>Challenges</span>, <span>Reuse</span> <span>Strategies</span> and <span>Security</span>,”</span> November. <a href="https://doi.org/10.5281/ZENODO.10141558">https://doi.org/10.5281/ZENODO.10141558</a>.
</div>
<div id="ref-monks_computer_2023" class="csl-entry" role="listitem">
Monks, Thomas, and Alison Harper. 2023. <span>“Computer Model and Code Sharing Practices in Healthcare Discrete-Event Simulation: A Systematic Scoping Review.”</span> <em>Journal of Simulation</em> 0 (0): 1–16. <a href="https://doi.org/10.1080/17477778.2023.2260772">https://doi.org/10.1080/17477778.2023.2260772</a>.
</div>
<div id="ref-naudet_data_2018" class="csl-entry" role="listitem">
Naudet, Florian, Charlotte Sakarovitch, Perrine Janiaud, Ioana Cristea, Daniele Fanelli, David Moher, and John P. A. Ioannidis. 2018. <span>“Data Sharing and Reanalysis of Randomized Controlled Trials in Leading Biomedical Journals with a Full Data Sharing Policy: Survey of Studies Published in <span>The</span> <span>BMJ</span> and <span>PLOS</span> <span>Medicine</span>.”</span> <em>BMJ</em> 360 (February): k400. <a href="https://doi.org/10.1136/bmj.k400">https://doi.org/10.1136/bmj.k400</a>.
</div>
<div id="ref-obels_analysis_2020" class="csl-entry" role="listitem">
Obels, Pepijn, Daniël Lakens, Nicholas A. Coles, Jaroslav Gottfried, and Seth A. Green. 2020. <span>“Analysis of <span>Open</span> <span>Data</span> and <span>Computational</span> <span>Reproducibility</span> in <span>Registered</span> <span>Reports</span> in <span>Psychology</span>.”</span> <em>Advances in Methods and Practices in Psychological Science</em> 3 (2): 229–37. <a href="https://doi.org/10.1177/2515245920918872">https://doi.org/10.1177/2515245920918872</a>.
</div>
<div id="ref-ostermann_advancing_2017" class="csl-entry" role="listitem">
Ostermann, Frank O., and Carlos Granell. 2017. <span>“Advancing <span>Science</span> with <span>VGI</span>: <span>Reproducibility</span> and <span>Replicability</span> of <span>Recent</span> <span>Studies</span> Using <span>VGI</span>.”</span> <em>Transactions in GIS</em> 21 (2): 224–37. <a href="https://doi.org/10.1111/tgis.12195">https://doi.org/10.1111/tgis.12195</a>.
</div>
<div id="ref-raff_step_2019" class="csl-entry" role="listitem">
Raff, Edward. 2019. <span>“A <span>Step</span> <span>Toward</span> <span>Quantifying</span> <span>Independently</span> <span>Reproducible</span> <span>Machine</span> <span>Learning</span> <span>Research</span>.”</span> In <em>Advances in <span>Neural</span> <span>Information</span> <span>Processing</span> <span>Systems</span></em>. Vol. 32. Curran Associates, Inc. <a href="https://proceedings.neurips.cc/paper/2019/hash/c429429bf1f2af051f2021dc92a8ebea-Abstract.html">https://proceedings.neurips.cc/paper/2019/hash/c429429bf1f2af051f2021dc92a8ebea-Abstract.html</a>.
</div>
<div id="ref-noauthor_revisiting_2022" class="csl-entry" role="listitem">
<span>“Revisiting Code Reusability.”</span> 2022. <em>Nature Machine Intelligence</em> 4 (10): 801–1. <a href="https://doi.org/10.1038/s42256-022-00554-9">https://doi.org/10.1038/s42256-022-00554-9</a>.
</div>
<div id="ref-samuel_computational_2024" class="csl-entry" role="listitem">
Samuel, Sheeba, and Daniel Mietchen. 2024. <span>“Computational Reproducibility of <span>Jupyter</span> Notebooks from Biomedical Publications.”</span> <em>GigaScience</em> 13 (January): giad113. <a href="https://doi.org/10.1093/gigascience/giad113">https://doi.org/10.1093/gigascience/giad113</a>.
</div>
<div id="ref-schwander_replication_2021" class="csl-entry" role="listitem">
Schwander, Björn, Mark Nuijten, Silvia Evers, and Mickaël Hiligsmann. 2021. <span>“Replication of <span>Published</span> <span>Health</span> <span>Economic</span> <span>Obesity</span> <span>Models</span>: <span>Assessment</span> of <span>Facilitators</span>, <span>Hurdles</span> and <span>Reproduction</span> <span>Success</span>.”</span> <em>Pharmacoeconomics</em> 39 (4): 433–46. <a href="https://doi.org/10.1007/s40273-021-01008-7">https://doi.org/10.1007/s40273-021-01008-7</a>.
</div>
<div id="ref-skaggs_reproducible_2015" class="csl-entry" role="listitem">
Skaggs, T.h., M.h. Young, and J.a. Vrugt. 2015. <span>“Reproducible <span>Research</span> in <span>Vadose</span> <span>Zone</span> <span>Sciences</span>.”</span> <em>Vadose Zone Journal</em> 14 (10): vzj2015.06.0088. <a href="https://doi.org/10.2136/vzj2015.06.0088">https://doi.org/10.2136/vzj2015.06.0088</a>.
</div>
<div id="ref-stagge_assessing_2019" class="csl-entry" role="listitem">
Stagge, James H., David E. Rosenberg, Adel M. Abdallah, Hadia Akbar, Nour A. Attallah, and Ryan James. 2019. <span>“Assessing Data Availability and Research Reproducibility in Hydrology and Water Resources.”</span> <em>Scientific Data</em> 6 (1): 190030. <a href="https://doi.org/10.1038/sdata.2019.30">https://doi.org/10.1038/sdata.2019.30</a>.
</div>
<div id="ref-stockemer_data_2018" class="csl-entry" role="listitem">
Stockemer, Daniel, Sebastian Koehler, and Tobias Lentz. 2018. <span>“Data <span>Access</span>, <span>Transparency</span>, and <span>Replication</span>: <span>New</span> <span>Insights</span> from the <span>Political</span> <span>Behavior</span> <span>Literature</span>.”</span> <em>PS: Political Science &amp; Politics</em> 51 (4): 799–803. <a href="https://doi.org/10.1017/S1049096518000926">https://doi.org/10.1017/S1049096518000926</a>.
</div>
<div id="ref-stodden_enabling_2018" class="csl-entry" role="listitem">
Stodden, Victoria, Matthew S. Krafczyk, and Adhithya Bhaskar. 2018. <span>“Enabling the <span>Verification</span> of <span>Computational</span> <span>Results</span>: <span>An</span> <span>Empirical</span> <span>Evaluation</span> of <span>Computational</span> <span>Reproducibility</span>.”</span> In <em>Proceedings of the <span>First</span> <span>International</span> <span>Workshop</span> on <span>Practical</span> <span>Reproducible</span> <span>Evaluation</span> of <span>Computer</span> <span>Systems</span></em>, 1–5. P-<span>RECS</span>’18. New York, NY, USA: Association for Computing Machinery. <a href="https://doi.org/10.1145/3214239.3214242">https://doi.org/10.1145/3214239.3214242</a>.
</div>
<div id="ref-stodden_empirical_2018" class="csl-entry" role="listitem">
Stodden, Victoria, Jennifer Seiler, and Zhaokun Ma. 2018. <span>“An Empirical Analysis of Journal Policy Effectiveness for Computational Reproducibility.”</span> <em>Proceedings of the National Academy of Sciences</em> 115 (11): 2584–89. <a href="https://doi.org/10.1073/pnas.1708290115">https://doi.org/10.1073/pnas.1708290115</a>.
</div>
<div id="ref-trisovic_large-scale_2022" class="csl-entry" role="listitem">
Trisovic, Ana, Matthew K. Lau, Thomas Pasquier, and Mercè Crosas. 2022. <span>“A Large-Scale Study on Research Code Quality and Execution.”</span> <em>Scientific Data</em> 9 (1): 60. <a href="https://doi.org/10.1038/s41597-022-01143-6">https://doi.org/10.1038/s41597-022-01143-6</a>.
</div>
<div id="ref-wilson_good_2017" class="csl-entry" role="listitem">
Wilson, Greg, Jennifer Bryan, Karen Cranston, Justin Kitzes, Lex Nederbragt, and Tracy K. Teal. 2017. <span>“Good Enough Practices in Scientific Computing.”</span> <em>PLOS Computational Biology</em> 13 (6): e1005510. <a href="https://doi.org/10.1371/journal.pcbi.1005510">https://doi.org/10.1371/journal.pcbi.1005510</a>.
</div>
<div id="ref-wood_push_2018" class="csl-entry" role="listitem">
Wood, Benjamin D. K., Rui Müller, and Annette N. Brown. 2018. <span>“Push Button Replication: <span>Is</span> Impact Evaluation Evidence for International Development Verifiable?”</span> <em>PLOS ONE</em> 13 (12): e0209416. <a href="https://doi.org/10.1371/journal.pone.0209416">https://doi.org/10.1371/journal.pone.0209416</a>.
</div>
<div id="ref-zhang_reporting_2020" class="csl-entry" role="listitem">
Zhang, Xiange, Stefan K. Lhachimi, and Wolf H. Rogowski. 2020. <span>“Reporting <span>Quality</span> of <span>Discrete</span> <span>Event</span> <span>Simulations</span> in <span>Healthcare</span>—<span>Results</span> <span>From</span> a <span>Generic</span> <span>Reporting</span> <span>Checklist</span>.”</span> <em>Value in Health</em> 23 (4): 506–14. <a href="https://doi.org/10.1016/j.jval.2020.01.005">https://doi.org/10.1016/j.jval.2020.01.005</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../pages/results_discussion.html" class="pagination-link" aria-label="Results discussion">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Results discussion</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../pages/framework.html" class="pagination-link" aria-label="Modifying the framework">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Modifying the framework</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>