---
title: "Relationship between reproduction and evaluation"
bibliography: ../references.bib
---

TODO: Add this page, to assess whether (and if so, how) there is a relationship between the evaluation (code and/or reporting) and how easy it was / able we were to reproduce

TODO: I'm also interested actually particularly in relationship between "reflections" being met, and reproduction.

*this could be more restructured into (a) reflections from evaluations, similar to as I have for reproductions, then supported by the side by side evidence, and then (b) adding that side by side evidence to the existing reflections from reproductions*

TODO: For reflections on evaluations, add reflection that a lack of provision of ORCID or citation information didn't have a big impact here, as I was choosing repositories that I had found from papers, so I already at least knew who the paper authors were. Although that doesn't mean that any attempted citation of the repository itself would've necessarily been correct, depending on whether the author list would be the same.

*add some scatter plots to repo evaluation but not sure how helpful they are*